# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Projects\DS_vpr\mainf.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(380, 220)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(380, 220))
        MainWindow.setMaximumSize(QtCore.QSize(380, 220))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 5, 181, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.labelIW = QtWidgets.QLabel(self.groupBox)
        self.labelIW.setGeometry(QtCore.QRect(20, 20, 41, 21))
        self.labelIW.setToolTip("")
        self.labelIW.setObjectName("labelIW")
        self.labelIF = QtWidgets.QLabel(self.groupBox)
        self.labelIF.setGeometry(QtCore.QRect(20, 50, 41, 21))
        self.labelIF.setToolTip("")
        self.labelIF.setObjectName("labelIF")
        self.labelVW = QtWidgets.QLabel(self.groupBox)
        self.labelVW.setGeometry(QtCore.QRect(20, 80, 41, 21))
        self.labelVW.setToolTip("")
        self.labelVW.setObjectName("labelVW")
        self.labelFP = QtWidgets.QLabel(self.groupBox)
        self.labelFP.setGeometry(QtCore.QRect(20, 110, 41, 21))
        self.labelFP.setToolTip("")
        self.labelFP.setObjectName("labelFP")
        self.spinBoxIW = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxIW.setGeometry(QtCore.QRect(80, 20, 91, 22))
        self.spinBoxIW.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxIW.setMinimum(42)
        self.spinBoxIW.setMaximum(50)
        self.spinBoxIW.setSingleStep(1)
        self.spinBoxIW.setProperty("value", 45)
        self.spinBoxIW.setObjectName("spinBoxIW")
        self.spinBoxIF = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxIF.setGeometry(QtCore.QRect(80, 50, 91, 22))
        self.spinBoxIF.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxIF.setMinimum(125)
        self.spinBoxIF.setMaximum(160)
        self.spinBoxIF.setProperty("value", 140)
        self.spinBoxIF.setObjectName("spinBoxIF")
        self.doubleSpinBoxVW = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxVW.setGeometry(QtCore.QRect(80, 80, 91, 22))
        self.doubleSpinBoxVW.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBoxVW.setDecimals(1)
        self.doubleSpinBoxVW.setMinimum(4.0)
        self.doubleSpinBoxVW.setMaximum(14.0)
        self.doubleSpinBoxVW.setSingleStep(0.1)
        self.doubleSpinBoxVW.setProperty("value", 8.0)
        self.doubleSpinBoxVW.setObjectName("doubleSpinBoxVW")
        self.spinBoxFP = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxFP.setGeometry(QtCore.QRect(80, 110, 91, 22))
        self.spinBoxFP.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxFP.setMinimum(40)
        self.spinBoxFP.setMaximum(140)
        self.spinBoxFP.setSingleStep(5)
        self.spinBoxFP.setProperty("value", 90)
        self.spinBoxFP.setObjectName("spinBoxFP")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(80, 170, 231, 31))
        self.ExitButton.setToolTip("")
        self.ExitButton.setObjectName("ExitButton")
        self.PredictButton = QtWidgets.QPushButton(self.centralwidget)
        self.PredictButton.setGeometry(QtCore.QRect(200, 10, 171, 31))
        self.PredictButton.setObjectName("PredictButton")
        self.labelHeigth = QtWidgets.QLabel(self.centralwidget)
        self.labelHeigth.setGeometry(QtCore.QRect(200, 50, 171, 21))
        self.labelHeigth.setObjectName("labelHeigth")
        self.labelWidth = QtWidgets.QLabel(self.centralwidget)
        self.labelWidth.setGeometry(QtCore.QRect(200, 100, 171, 21))
        self.labelWidth.setObjectName("labelWidth")
        self.labelPredictHeigth = QtWidgets.QLabel(self.centralwidget)
        self.labelPredictHeigth.setGeometry(QtCore.QRect(200, 80, 161, 21))
        self.labelPredictHeigth.setText("")
        self.labelPredictHeigth.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredictHeigth.setObjectName("labelPredictHeigth")
        self.labelPredictWidth = QtWidgets.QLabel(self.centralwidget)
        self.labelPredictWidth.setGeometry(QtCore.QRect(200, 130, 161, 21))
        self.labelPredictWidth.setText("")
        self.labelPredictWidth.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredictWidth.setObjectName("labelPredictWidth")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Прогнозирование размеров сварного шва"))
        self.groupBox.setTitle(_translate("MainWindow", "Введите параметры"))
        self.labelIW.setText(_translate("MainWindow", "IW:"))
        self.labelIF.setText(_translate("MainWindow", "IF:"))
        self.labelVW.setText(_translate("MainWindow", "VW:"))
        self.labelFP.setText(_translate("MainWindow", "FP:"))
        self.ExitButton.setText(_translate("MainWindow", "Выход"))
        self.PredictButton.setText(_translate("MainWindow", "Получить прогноз"))
        self.labelHeigth.setText(_translate("MainWindow", "Прогнозируемая глубина:"))
        self.labelWidth.setText(_translate("MainWindow", "Прогнозируемая ширина:"))
